from tkinter import *
route = Tk()
route.title("getting started with widgits")
route.geometry("400x300")
l = Label(text = "hey there!!!",fg="white",bg = "blue",height = 1,width = 300)
l.pack()
name_lvl = Label(text="enter ur full name ",bg = "pink")
name_entry = Entry()
name_lvl.pack()
name_entry.pack()
textbox = Text(height = 3)
btn = Button(text = "begin",height = 1,bg = "green",fg = "red")
btn.pack()
textbox.pack()
route.mainloop()
